### ISSUE TITLE
Error logging via syslog

### ISSUE THREAD

**Issue by jpmens** [owntracks/recorder#10]
so that we can daemonize `ot-recorder` and/or run it under whatever

**Comment by binarybucks** [comment]
or just provide a systemd service file and log to stdout/stderr.

Mit freundlichen Grüßen / With kind regards
Alexander Rust

On 28 Aug 2015, at 09:59, JP Mens <notifications@github.com> wrote:

so that we can daemonize ot-recorder and/or run it under whatever

—
Reply to this email directly or view it on GitHub
<https://github.com/owntracks/recorder/issues/10>.

**Comment by jpmens** [comment]
Is there a reason you keep imposing systemd on me? ;-) I know plenty of systems which don't have that ... (Even though it's maybe politically incorrect of me to say that nowadays. :-)

**Comment by binarybucks** [comment]
all our hosted systems use systemd, that's why.

On Fri, Aug 28, 2015 at 3:14 PM, JP Mens <notifications@github.com> wrote:

> Is there a reason you keep imposing systemd on me? ;-) I know plenty of
> systems which don't have that ... (Even though it's maybe politically
> incorrect of me to say that nowadays. :-)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/owntracks/recorder/issues/10#issuecomment-135772158>.
>



-- 
Mit freundlichen Grüßen / With kind regards
Alexander Rust

**Comment by jpmens** [comment]
Do recall please that recorder is intended to be a generalized utility for people to _record_ their OwnTracks location publishes at home.
