### ISSUE TITLE
Encrypted payloads for device ID's with a space

### ISSUE THREAD

**Issue by willcosgrove** [owntracks/recorder#108]
I was having trouble setting up encrypted payloads.  My device id is `iPhone 6s`, and my User is `Will`.  According to the readme, I figured the key name should be `will-iphone-6s`.  But that didn't work.  I tried a lot of variations, but none worked.  I eventually caved, and renamed my device id to `Phone`.  I was then able to get encryption to work with the key `Will-Phone` (not all lower case as specified in the readme).

I tried following the source, but I'm not well versed in C.  How would the key have looked with the device ID with a space?

Also, really cool project!  Looking forward to playing around with it more.

**Comment by jpmens** [comment]
Ooh, the space in the device name ... That could be a bug on our side. The key would have been found in the lmdb database as `will-iphone 6s` (including the blank), but I don't think we can enter that into the db with `ocat`, because I split the input at the first space.

The only workaround I can think of (but I hesitate to implement this) is to specify a separator (eg TAB, or `:`) in the `ocat` utility.

As to the lowercasing (or not lowercasing) of the key, I'll verify later.

**Comment by jpmens** [comment]
So I've addressed this just now. You were right: it was buggy in that the username and device name were not lowercased; this is fixed. I've also done the following: spaces are converted to dashes. Would appreciate your testing this if you have pulled from Github.

**Comment by willcosgrove** [comment]
Wow, that was fast!  Thanks :)
I've got it installed on a raspberry pi from the apt repository.  I'll play around with it tonight after work and see if I can get it compiled and I'll try it out.  Thanks again for your help!
