### ISSUE TITLE
Segfault with --debug

### ISSUE THREAD

**Issue by jpmens** [owntracks/recorder#150]
binarybucks reports `ot-recorder --debug` segfaults on CentOS 7.2/64` (latest commit 6638a3b20b5120e70d7f47f4edba7cdb43459a21)

Omiting `--debug` doesn't produce the fault.

Payloads are encrypted.

**Comment by graugans** [comment]
Just an idea not serious about it. When calling libconfig ``config_lookup_string`` the function may return an NULL pointer as value. This is due to the empty string. But the return value is ``CONFIG_TRUE`` this results in a call of ``strdup`` with ``NULL`` as argument what [is not defined](http://stackoverflow.com/questions/6432384/strdup-dumping-core-on-passing-null) -> **segfault**.
