### ISSUE TITLE
Debian Stretch

### ISSUE THREAD

**Issue by JohnnyDevine** [owntracks/recorder#201]
Does Recorder work on stretch yet? I have mosquitto working from the debian packages contained within stretch.

JD

**Comment by jpmens** [comment]
Since about 27 seconds, and just for you, yes! :-)

The problem: you're going to have to test it for us please. I've updated the [repository documentation](http://repo.owntracks.org/README.txt), and it would be great if you could help us verify that that's all correct and works.

As a special thank you for doing so, you will get the next version of OwnTracks Recorder *free*! :-)

**Comment by JohnnyDevine** [comment]
Will do.....and thank you :)

**Comment by JohnnyDevine** [comment]
Seems to install OK

root@stretch:/var/spool/owntracks/recorder/store/last# ocat -v
This is OwnTracks Recorder, version 0.7.2
built with:
	WITH_MQTT = yes
	WITH_HTTP = yes
	WITH_LUA  = yes
	WITH_ENCRYPT = yes
	WITH_PING = yes
	WITH_KILL = yes
	CONFIGFILE = "/etc/default/ot-recorder"
	STORAGEDEFAULT = "/var/spool/owntracks/recorder/store"
	STORAGEDIR = "/var/spool/owntracks/recorder/store"
	DOCROOT = "/usr/share/owntracks/recorder/htdocs"
	GHASHPREC = 7
	DEFAULT_HISTORY_HOURS = 6
	JSON_INDENT = "NULL"
	LIBMOSQUITTO_VERSION = 1.4.12
	MDB VERSION = LMDB 0.9.16: (August 14, 2015)
	SODIUM VERSION = 1.0.8
	GIT VERSION = 0.7.2-2-g8aa745efc3


I am not getting any location info from the iPhone, but I think that is a config thing on my part, its a while since I set one of these up

JD

**Comment by JohnnyDevine** [comment]
OK got location stuff working now, looks to be working OK in stretch, I will keep you updated, anything specific you would like me to test?

JD

**Comment by jpmens** [comment]
If you are seeing location data on the map and in the table, and the records in store are being updated, you're good to go. Thank you for your help.

**Comment by JohnnyDevine** [comment]
Yep all working fine, remeber to amend the documentation for a stretch install, it does not need the repositories for installing mosquitto, they are part of debian stretch now, indeed if you do go down the path of using the repositories for mosquitto, it doesn't work....
http://repo.mosquitto.org/debian stretch/main amd64 Packages [2,390 B]    
The following packages have unmet dependencies:
mosquitto : Depends: libssl1.0.0 (>= 1.0.1) but it is not installable
Depends: libwebsockets3 (>= 1.2) but it is not installable
mosquitto-clients : Depends: libmosquitto1 (= 1.4.11-0mosquitto1) but it is not going to be installed.

JD

**Comment by juzam** [comment]
thanks @JohnnyDevine Speaking about our Docker image  we switched to the mosquitto repos because the packages provided were more up to date than the Debian provided ones at that time (on jessie)  Stretch now provides mosquitto version `1.4.10-3` which I still haven't tested against this CVE https://mosquitto.org/2017/05/security-advisory-cve-2017-7650/ but it's not marked as a security update on the Debian site.

Where did you find the reference to the Debian mosquitto repos? I can't find it in the file @jpmens linked before nor in the recorder repository.

**Comment by JohnnyDevine** [comment]
Does this help, it looks like stretch 1.4.10-3 has the patch ?

https://www.debian.org/security/2017/dsa-3865

**Comment by jpmens** [comment]
@juzam it turns out @JohnnyDevine is right of course: our README.md says

> We create packages for releases for a few distributions. Please note that these packages depend on libmosquitto1 from the [Mosquitto project](http://mosquitto.org/downloads)

I will rephrase that.

Thank you very much @JohnnyDevine for your help; much appreciated!

**Comment by juzam** [comment]
@jpmens ah! I missed that of course. 
also thank you @JohnnyDevine for pointing me in the right direction by providing proof of patch and for all the testing :)

**Comment by JohnnyDevine** [comment]
Most Welcome........Glad I could be of some assistance :)
