### ISSUE TITLE
ot-recorder command line options (how to specify password in terminal) Debian/Ubuntu 16.04

### ISSUE THREAD

**Issue by sanyaade-iot** [owntracks/recorder#218]
Hello Everybody,

Happy new year in advance.

How do someone specify or overide password from console.
**e.g. ./ot-recorder  --http-port 8083 --user "joemum" --pass "letmein"**
I have tried all possible permutation I can think of but I get back:
./ot-recorder: unrecognized option '--pass'  or whatever I pass to it

Also ot-recorder is not loading this from: ot-recorder.default or config.mk . Looks like I need to recompile it again for the changes to those files to take place

I have tried everything before asking for help.

Please help me! Many thanks!

God blesses!!!

Best regards,
Sanyaade

**Comment by sanyaade-iot** [comment]
Hello Everybody,

Its me again but I got things sorted out now by modifying the configuration file only. It will be nice to able to pass the password parameter via command line. MySQL, TelNet, RPC apps allows this feature.

Many thanks!

God blesses!!!

Best regards,
Sanyaade

**Comment by shymega** [comment]
This issue can be closed - if the password parameter is still wanted, then an separate issue can be created on this repo. Perhaps even a PR could be made? :)

**Comment by shymega** [comment]
In fact, I could make a PR. Might as well challenge myself with some good 'ol C. :)

**Comment by shymega** [comment]
(Deleted previous comments; misunderstood the error)

@sanyaade-iot I understand the issue now.

The password parameter is not available via the command line arguments - I would make a reasonable guess that the authors of this program didn't add a `--pass` or `-password` parameter, because in a *nix system, any user **can** see the parameters passed to a program. Generally, the idiomatic way to solve this problem is to either, a) provide the password in a configuration file or b) provide it in via an environment variable.

If you run `./ot-recorder --help`, you will notice at the bottom of the listing, these variables:

```
(..snip..)

Options override these environment variables:
  $OTR_STORAGEDIR
  $OTR_BROWSERAPIKEY
  $OTR_HOST		MQTT hostname
  $OTR_PORT		MQTT port
  $OTR_USER
  $OTR_PASS
  $OTR_CAFILE		PEM CA certificate chain
```

In answer to your question, you cannot provide the password via the command line, and it would not be advisable to allow that option, for the reasons I guessed at above - although I'm reasonably sure I'm correct. 

The best solution to your issue would be to export the environment variable `OTR_PASS` in a wrapper script before running ot-recorder, like so:

```
#!/bin/sh

export OTR_PASS="letmein"

./ot-recorder --http-port 8083 --user "joemum"
```

This (example) wrapper script would then work as expected.

I hope this helps with your issue. 😄

**Comment by sanyaade-iot** [comment]
@shymega

Okay, I will fork and ext/modify the source code to allow password passed from command line. This feature is needed for my teachings/research (also for remote usage). As you have stated above while exporting only password while other parameters be passed via command line. But as you have mentioned, I will respect the view of the developer(s). 

Many thanks for your reply and support!

God blesses!!!

Best regards,
Sanyaade
