### ISSUE TITLE
Error 404 trying to access /pub to publish location

### ISSUE THREAD

**Issue by DarkForce42** [owntracks/recorder#255]
Hi
I've been trying to set-up ot-recorder with nginx as proxy.
When I try to publish the location the Android app shows "Not available" as Endpoint store message. When I visit the https://domain/pub?u=user&d=device or https://domain/pub&u=user&d=device via the browser the server gives the error "ERROR 404: Not Found".

The same happens when I use curl with a direct call towards http://192.168.2.9/pub etc...

Anyone got a clue what this could be ?

**Comment by jpmens** [comment]
Assuming `domain` and `192.168.2.9` point to your proxy, this sounds quite as though the proxy isn/t configured correctly with a backend of the Recorder. How about you show us the pertinent portion of your nginx.conf?

**Comment by ldruschk** [comment]
The server always returns 404 for `GET` requests on `/pub` since this is not used for anything. Try sending a `POST` request instead using `curl -XPOST http://localhost:8083/pub`, which is what is also used by the app and should return `[]` when working correctly.

If that works, nginx is probably configured correctly and there is another issue.

**Comment by jpmens** [comment]
@DarkForce42 have you been able to solve this?
