### ISSUE TITLE
http mode not sending or recorder not logging event messages

### ISSUE THREAD

**Issue by aarondvail** [owntracks/recorder#276]
I have both an android device and an iOS device transmitting in http mode ( as well as a 2nd iOS device in MQTT over VPN). 

Both iOS are using version 9.9.3 and the android is using 2.1.2. and I'm running recorderd in Docker with the latest image available.

the MQTT device is transmitting the event messages without any issue, however, both http devices are not. if i switch them to MQTT (over VPN) they do, but I need http to work.... Ideas?

**Comment by jpmens** [comment]
We cannot possibly know what you’ve configured and how. How about showing?

**Comment by aarondvail** [comment]
![cipad-owntracks-redacted](https://user-images.githubusercontent.com/36673283/50851325-80beb400-134a-11e9-882e-72483287bf2b.png)
![cipad-owntracks](https://user-images.githubusercontent.com/36673283/50851327-80beb400-134a-11e9-9b88-72c16dde23ff.png)

These are both the iOS devices (key data redacted) the MQTT one works, and the HTTP one doesn't. The only difference on the host (aside from the https or mqtt) is the /pub?u=userid&d=deviceid

the mosquitto.acl has the same permissions (except for the userid differences)

**Comment by jpmens** [comment]
Things to check

- is your Recorder protected by a firewall?
- can you reach via a TCP connection (e.g. by a Web browser) the Recorder port?
- what does the Recorder show you on its console (or logs; check docker docs for how) when you publish from the HTTP client?

**Comment by jpmens** [comment]
the HTTP service will not show up in the Mosquitto log; Mosquitto is your MQTT broker.

If the HTTP device is showing up in the "TABLE of current locations", I am severely confused: you started off by saying

> however, both http devices are not [showing up]

So the HTTP device is showing up.

What then is the issue?

**Comment by aarondvail** [comment]
I am very sorry for the confusion.... I'm trying to use this with my OpenHAB... and it's polling the MQTT connections for geolocation triggers... 

and OpenHAB is looking owntracks/<userid>/<deviceid>/event messages for the triggers... 
the MQTT device posts the event messages
the HTTP devices posts only the owntracks/<userid>/<deviceid> but never to the owntracks/<userid>/<deviceid>/events

**Comment by jpmens** [comment]
MQTT and HTTP are completely different protocols, and what you are trying to accomplish using OwnTracks and OpenHAB via MQTT is not (easily) possible in HTTP mode. The reason is that when your mobile devices (iOS) POST a HTTP message to the Recorder, it's exactly that piece of software (the Recorder) which gets the location update, and none other, in particular not the MQTT broker / bus and thus also not OpenHAB.

One solution (but this might be more work than you're willing to invest) is to configure the Recorder to publish message it obtains via HTTP (from iOS) onto the MQTT bus. This is possible with our Lua integration (and it is explained a bit in the documentation). It's not really for the faint of heart, but give it a go if you feel up to it. :-)

What interests me at this point is: if MQTT works on your mobile devices and you're happy with that, why do you want to use HTTP mode?

**Comment by aarondvail** [comment]
Thanks, I'll look into it, I've been having so much fun with it this far :D 

The reason for the HTTP is to avoid the necessity for MQTT over VPN... Cellular service often disconnects VPN when switching towers and has a tough time reconnecting and I'd like to keep the OwnTracks logging as close to real time as possible

**Comment by jpmens** [comment]
Glad you're enjoying it -- so do we. :-)

You can do MQTT without VPN, if you ensure you do proper ACLs, use decent passwords and set up TLS correctly, you have have a pretty secure MQTT broker connection
