### ISSUE TITLE
Get Friends with API?

### ISSUE THREAD

**Issue by metal450** [owntracks/recorder#301]
Is it possible to query a given user's friends with the API (https://github.com/owntracks/recorder/blob/master/API.md)?

I tried http://server/api/0/friends?user=name&device=dev

...But it said "No Comprendo" :)

**Comment by jpmens** [comment]
I think `no comprendo` is a rather good response to a request which doesn't exist, don't you? :-) 

No, this is not possible.

Care to elaborate what you'd use it for?

**Comment by metal450** [comment]
In https://github.com/linusg/owntracks-ui, to enable a UI where (like on the mobile apps), users can only view the locations of their friends :)

**Comment by jpmens** [comment]
I don't think we can currently implement this: in HTTP mode we know which friends a user has because they are configured in an LMDB database; (`ocat --dump=friends`), but in MQTT mode we don't have this information; only the MQTT broker with the aid of its ACL knows these relationships.

As such we can't offer this agnostically over the API.

(Unless of course, somebody has an idea I've not considered. :-) )
