### ISSUE TITLE
Feature request: Alternative path for views JSON

### ISSUE THREAD

**Issue by tobru** [owntracks/recorder#305]
When running the recorder on Kubernetes one like me would love to store views JSON in a ConfigMap and mount it into the Pod. One drawback of mounting a ConfigMap into a Pod is that it replaces the content of the whole path. So if I mount a ConfigMap under `/htdocs/views` it would also replace `vmap.html` which I do not want to store in the ConfigMap.

I suggest to add the possibility to have an alternative folder where views JSON can be stored and picked up by the recorder.

(Due to my lack of C-programming skills I can't do a PR - I would have loved to provide one)

**Comment by jpmens** [comment]
I'm not familiar with Kubernetes (and only yesterday heard the term ConfigMap), but it sounds reasonable. It's a shame you won't do a PR because that leaves it to me ... #sigh :-)

`VIEWSUBDIR` is currently defined to `views` which renders files as `/htdocs/views` as you correctly say. Do you think it would suffice if we just made this configurable through a program option `ot-recorder --viewsdir /path/to/configmap` ?

**Comment by jpmens** [comment]
I've added the option; I'd appreciate your testing.

**Comment by tobru** [comment]
You're not familiar with Kubernetes, I'm not familiar with C. Great match 😄 

This option is absolutely what I was thinking about... I must admit, I didn't think you'll be _that_ quick in implementing this little gem! This is mind blowing 💨 

As I'm currently "stuck" in a campervan, enjoying Holidays 🌞, thinking about how to improve my future travelling tracking and just using a simple little Chromebook without good access to my Kubernetes cluster, it takes a few days until I get my hands dirty testing this command-line option.

The result of the testing will be a blog-post describing how I run OwnTracks recorder on Kubernetes (already doing it, just without views) and a Gin for you, the next time we meet 🎉

**Comment by jpmens** [comment]
Closing as stale
