### ISSUE TITLE
Not init properly. No data saved in DB 

### ISSUE THREAD

**Issue by qk4l** [owntracks/recorder#316]
Hi, 

I'm trying to setup ot-recorder in HTTP mode only and saved data from Android device but get failed and leave out of ideas whats going on.

My setup:
OS: Debian 9.9
Package: ot-recorder (from http://repo.owntracks.org/debian)
Version: 0.8.4-0-deb9.6
Config:
```
$ egrep -v '(^#|^$)' /etc/default/ot-recorder 
OTR_PORT=0
OTR_HTTPPORT=8083
OTR_GEOKEY="opencage:XXX"
OTR_TOPICS="owntracks/#"
```
After package install storage dir does not contains last/res folders that cause error message from `ocat`. I tried to call `ot-recorder --initialize` but this does not help.

Ok, may be that folders are creating after first report from client.

I configured Android app but folders and continue..

I see request from client and responses with code 200 from server (with html page titled  <title>Recorder</title>).

But nothing saved in database absolutely =(
```
# ls /var/spool/owntracks/recorder/store/ -Rl
/var/spool/owntracks/recorder/store/:
total 4
drwxr-xr-x 2 owntracks root 4096 Aug 25 14:18 ghash

/var/spool/owntracks/recorder/store/ghash:
total 36
-rw-r--r-- 1 owntracks root 32768 Aug 25 14:18 data.mdb
-rw-r--r-- 1 owntracks root  8192 Aug 25 15:18 lock.mdb
```

And not errors anywhere even in debug mode -  https://gist.github.com/qk4l/de5d72023f66c2786ee387931124a25d

Could you please lead me what could be wrong?

Thanks.

**Comment by jpmens** [comment]
The `rec` and `last` directories are created on-the-fly when Recorder gets data.

It appears to me as though your Android device isn't finding your installation. Judging by the Recorder configuration you've posted above, your Android should be configured for HTTP mode, the IP/name of your Recorder server, HTTP port 8083 (warning: *not* `https`) and a username.

By pressing _publish_ on your Android device you should see location data being published in the Recorder's console. (If need be, stop the service and start the program manually so that you see the output.)

**Comment by qk4l** [comment]
I missed a path `/pub`

> The Recorder supports HTTP mode out of the box at the /pub end point.

Sorry for issue and thank you for what you are doing!
