### ISSUE TITLE
merge / import old data

### ISSUE THREAD

**Issue by stevanov** [owntracks/recorder#357]
I went from local install of ot-recorder to a docker install since i was serveral versions behind. I've got over a year's worth of recorder data that i want to carry over to the new install. I attempted to just put the data of my old 'store' dir in the new one but ot-recorder wouldnt start. 

Is there a recommended way to import old .rec files into a new database? I read the readme buy didnt find anything about it

**Comment by jpmens** [comment]
You can easily "import" .rec files from a previous installation by 
placing them in the appropriate directories of the new installation in 
the rec/username/devicename/ directory, ensuring the recorder can read 
(and if necessary because it's the current year-month, write) them.

Stop the recorder before doing so and restart it afterwards. Note that 
you'll get the positioning data only that way; any geo-lookups are kept 
in the lmdb database which you will possibly want to export and 
re-import with ocat.

**Comment by stevanov** [comment]
@jpmens Thank you, I wasn't completely sure if this was 'expected' or 'allowed' behaviour. Managed to joint two folders and even merge the overlapping month with a simple ```cat secondhalf.rec >> firsthalf.rec``` 

Was happy to see that the contents of .rec files look human readable 👍

**Comment by jpmens** [comment]
Glad it worked. Yes it's halfways readable because we store the received JSON after the timestamp and a TAB.
