### ISSUE TITLE
Built-in webserver not functioning

### ISSUE THREAD

**Issue by Luuk2016** [owntracks/recorder#392]
I've set up the recorder using Docker on my Synology NAS.
The recorder connects to my MQTT server, but when trying to access the built-in webserver by going to IP:8083/last/index.html, the browser shows me an "The connection has been reinitialized" error.
I have used the same steps that are mentioned in the documentation: https://owntracks.org/booklet/clients/recorder/

Thanks.

**Comment by jpmens** [comment]
Try and obtain the logs from your sinology's docker panel please, and show the startup of the container as well as the logs that occur at the moment you try to connect with your Web browser.

**Comment by Luuk2016** [comment]
Thanks for the fast response.
The following logs are created when running the container and trying to access the webserver:
<img src="https://i.imgur.com/fAMs8fQ.png"/>

**Comment by jpmens** [comment]
The Recorder is listening on 127.0.0.1 (loopback interface) of the container. Please configure it to listen to 0.0.0.0 at which point your Synology will be able to direct requests to it. 

In order to do so, invoke Recorder with `ot-recorder --http-host 0.0.0.0` when launching it.

That should do the job.

**Comment by Luuk2016** [comment]
When running the command it's giving a "port is already in use" error: 
![afbeelding](https://user-images.githubusercontent.com/24903547/182361649-23f3608f-e4d5-4f29-9e4c-236599d2275f.png)
Isn't it possible to pass 0.0.0.0 by using a env variable? In the documentation i saw that there is a "OTR_HTTPHOST" variable, is this something different?

**Comment by jpmens** [comment]
If you run the command while the container is running then the port will be in use, so you'll please have to change the container configuration.

OTR_HTTPHOST is (unfortunately) not yet an actual variable, so that will not work.

**Comment by linusg** [comment]
Related:
- https://github.com/owntracks/recorder/issues/388
- https://github.com/owntracks/frontend/issues/85
- https://github.com/owntracks/docker-recorder/issues/54
- https://github.com/owntracks/docker-recorder/issues/55
- https://github.com/owntracks/docker-recorder/issues/58

@Luuk2016 you can find examples for the mentioned container configuration changes in the `docker-recorder` issues linked above.

(I, too, ran into this the other day while setting up a second dockerized OwnTracks - would be awesome to have an env variable for this eventually instead of having to tweak the config file or provide a custom `entrypoint` with changed command line options)

**Comment by jpmens** [comment]
On it, @linusg, right now, as we speak.

**Comment by Luuk2016** [comment]
@jpmens @linusg 
It's working now, thanks!
I've changed my setup by adding: "entrypoint: ot-recorder --http-host 0.0.0.0 owntracks/#" in my Docker compose file.

**Comment by jpmens** [comment]
Glad you got it going, @Luuk2016

**Comment by jpmens** [comment]
Fix will be in next version: 

```
$ OTR_HTTPHOST=10.0.99.137 OTR_HTTPPORT=9004 ot-recorder
Aug  2 15:07:22  ot-recorder[33755] <Debug>: version 0.9.0 starting with STORAGEDIR=JP
Aug  2 13:07:22  ot-recorder[33755] <Info>: connecting to MQTT on 127.0.0.1:1883 as clientID otrosm6 without TLS
Aug  2 13:07:22  ot-recorder[33755] <Info>: Using access log at JP/access.log
Aug  2 13:07:22  ot-recorder[33755] <Info>: HTTP listener started on 10.0.99.137:9004
```
