### ISSUE TITLE
repo.owntracks.org not working

### ISSUE THREAD

**Issue by j7eich** [owntracks/recorder#489]
File https://repo.owntracks.org/README.txt (linked from https://github.com/owntracks/recorder/README.md) is not found, opening https://repo.owntracks.org/ in browser shows "hihi" only.

**Comment by jpmens** [comment]
Thanks for  your report. Indeed something appears to have changed on Github's rendering because the URL is actually http only (i.e not https as apt I believe still doesn't support that).

The readmy actually contains this text (here as screenshot in order to ensure we see what's there):

![rabbit-11216](https://github.com/user-attachments/assets/36062ec1-8145-40bb-9a8b-b5deb4a9eb26)

**Comment by j7eich** [comment]
uh, thanks, my bad!
