### ISSUE TITLE
Where is ocat?

### ISSUE THREAD

**Issue by bouton** [owntracks/recorder#495]
Stupid beginner (linux) issue
I have successfully installed owntracks recorder and frontend via docker. Both work fine.
Now trying to use ocat to export a gpx file.
when I use the console of the docker container and type ocat --list (for example) I get error -bash: ocat: command not found
I cant find it with find command either

Am I missing an install?

What is the path to the command?

Again apologies for newbieness of this.

**Comment by jpmens** [comment]
it ought to be in /usr/bin/ocat

**Comment by Jachimo** [comment]
It is in `/usr/bin/ocat` for me, but I did not install via Docker—I used the "quicksetup" method. Unless you are already quite familiar with Docker, I would recommend using this route rather than putting the app in a container, since (IMO) that adds an additional level of complexity.

My guess is that with a Dockerized install, you need to be inside one of the Docker containers in order to run the `ocat` binary.  So probably you need to use `docker exec -it CONTAINERNAME ocat` where `CONTAINERNAME` is the name of the Docker container that you're running OwnTracks' stuff from.

**Comment by jpmens** [comment]
What @Jachimo writes is accurate.

Now closing as answered.
